# Generated by Django 5.0.6 on 2026-02-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItemStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('type', models.CharField(choices=[('ROD', 'Rod'), ('BAIT', 'Bait')], default='BAIT', max_length=15)),
                ('price', models.PositiveIntegerField()),
                ('effect', models.FloatField()),
            ],
        ),
    ]
