# Generated by Django 5.0.6 on 2026-02-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_seed_item_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstore',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
