# Generated by Django 5.0.6 on 2026-02-02 10:07

from django.db import migrations

ITEM_CODES = {
    "Basic Rod": "ROD_BASIC",
    "Super Rod": "ROD_SUPER",
    "Ultra Rod": "ROD_ULTRA",
    "Basic Bait": "BAIT_BASIC",
    "Super Bait": "BAIT_SUPER",
    "Ultra Bait": "BAIT_ULTRA",
}


def set_codes(apps, schema_editor):
    ItemStore = apps.get_model("store", "ItemStore")

    for item in ItemStore.objects.all():
        try:
            item.code = ITEM_CODES[item.name]
        except KeyError:
            raise ValueError(f"No code for the item '{item.name}'")
        item.save(update_fields=["code"])


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_itemstore_code"),
    ]

    operations = [
        migrations.RunPython(set_codes),
    ]
