# Generated by Django 5.0.6 on 2026-02-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_set_item_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemstore',
            name='code',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
    ]
