# Generated by Django 5.0.6 on 2026-03-25 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_itemstore_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstore',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
