# Generated by Django 5.0.6 on 2026-01-26 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('fish_id', models.PositiveIntegerField(default=1, unique=True)),
                ('description', models.CharField(max_length=100)),
                ('habitat', models.CharField(choices=[('RIVER', 'River'), ('LAKE', 'Lake'), ('SEA', 'Sea'), ('OCEAN', 'Ocean')], default='RIVER', max_length=15)),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('LEGENDARY', 'Legendary')], default='COMMON', max_length=15)),
                ('base_weight', models.FloatField(default=0.0)),
                ('base_price', models.PositiveIntegerField(default=10)),
            ],
        ),
    ]
