# Generated by Django 5.0.6 on 2026-02-02 08:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fishers', '0003_remove_fisher_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('description', models.TextField(blank=True)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('is_equipped', models.BooleanField(default=False)),
                ('caught_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('fisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='fishers.fisher')),
            ],
            options={
                'ordering': ['-caught_at'],
                'unique_together': {('fisher', 'content_type', 'object_id', 'caught_at')},
            },
        ),
    ]
