# Generated by Django 5.0.6 on 2026-02-03 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish', '0002_seed_fish'),
        ('fishers', '0003_remove_fisher_email'),
        ('inventory', '0001_initial'),
        ('store', '0005_alter_itemstore_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='FisherFish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caught_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('length', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='fish.fish')),
                ('fisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caught_fish', to='fishers.fisher')),
            ],
            options={
                'ordering': ['-caught_at'],
            },
        ),
        migrations.CreateModel(
            name='FisherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_equipped', models.BooleanField(default=False)),
                ('acquired_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.PositiveBigIntegerField(default=1)),
                ('fisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itmes', to='fishers.fisher')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='store.itemstore')),
            ],
            options={
                'unique_together': {('fisher', 'item')},
            },
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
    ]
