# Generated by Django 5.0.6 on 2026-02-04 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fishers', '0003_remove_fisher_email'),
        ('inventory', '0002_fisherfish_fisheritem_delete_inventoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fisheritem',
            name='fisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fishers.fisher'),
        ),
    ]
