# Generated by Django 5.0.6 on 2026-01-20 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fishers', '0002_fisher_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fisher',
            name='email',
        ),
    ]
